services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  movie_graphql:
    restart: unless-stopped
    container_name: 'movie_graphql'
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    links:
      - postgres
    depends_on:
      - postgres