services:
  movie_graphql:
    restart: unless-stopped
    container_name: 'movie_graphql'
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    links:
      - postgres
  
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "0.0.0.0:5432:5432"
    restart: unless-stopped
